### PR TITLE
Updated A-Team search committee language from recently passed amendment

### PR DESCRIPTION
**Pull request by cmbuck**
Does not include copy-edits made during forum

### CODE REVIEW

**Comment by defjosiah** [comment]
Do you think that you could add the copy-edits from forum, just so that we can commit this once?

**Comment by cmbuck** [comment]
Since the copy edits were not included in the minutes I don't know what they were.  Otherwise, yes, I would have included them.

**Comment by defjosiah** [comment]
Chill, feel free to merge!

**Comment by cmbuck** [comment]
image
It looks like I don't have that option?

**Comment by cmbuck** [comment]
image
It looks like I don't have write privs

**Comment by defjosiah** [comment]
Interesting, I'll check it out.

**Pull request merged**
